name = "StarMMO"
author = "StarM8"
version = "[1.0.0]"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f748181b2b484d6d3650c7ca4348bf070fa2cfbd24a85cdb52b9dcf442f2ed91"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
