name = "StarMMO"
author = "StarM8"
version = "[1.0.0]"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07f9b7be9942d5d460791ef0ec1c7ddf782fe84c260a2c0b0e50a630d4e1e390"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
