name = "StarMMO"
author = "StarM8"
version = "[1.0.0]"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88b9ee18826e7750bd46f1f3bd1af9133116739f35907abfb4616abbcf762f7b"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
